language: node_js
node_js: 10.15.3
cache:
  directories:
    - node_modules
branches:
  only:
    - dev

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
  - git config user.name "elegantYU"
  - git config user.email "845384559@qq.com"
  - sed -i'' "s~https://github.com/elegantYU/elegantYU.github.io.git~https://${ACCESS_TOKEN}@github.com/elegantYU/elegantYU.github.io.git~" _config.yml
script:
  - cd themes/nayo
  - npm install
  - npm run build
  - cd ..
  - cd ..
  - hexo clean
  - hexo g
  - hexo d
