#---------------------------
# Material-T
# Author: rook1e
# Github: https://github.com/0x2e/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: /favicon.png
apple_touch_icon: /apple-touch-icon.png


#---------------------------
# 首页
# Index Page
#---------------------------
index: 
  banner_img: https://w.wallhaven.cc/full/g8/wallhaven-g82m1d.png
  banner_img_height: 100  # available: 0 - 100
  subtitle:
    enable: true
  auto_excerpt:
    enable: true
    length: 300
  post_url_target: _self  # available: _blank | _self
  post_info:
    enable: false


#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    Home: /
    Archives: /archives/
    About: /about/


#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  banner_img: https://w.wallhaven.cc/full/6k/wallhaven-6kwrdx.png
  banner_img_height: 70  # available: 0 - 100
  toc: 
    enable: true
  highlight:
    enable: true
    theme: tomorrow-night-eighties # available: github | tomorrow | tomorrow-night | tomorrow-night-eighties
  copyright:
    enable: true
    content: 本博客所有文章除特别声明外，均采用 <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC">CC BY-SA 3.0协议</a> 。转载请注明出处！
  comments: 
    enable: true
    type: gitment  # available: disqus | valine

# Gitment
gitment:
  enable: true
  mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
  count: true # Show comments count in post meta area
  lazy: false # Comments lazy loading with a button
  cleanly: false # Hide 'Powered by ...' on footer, and more
  language: # Force language, or auto switch by theme
  github_user: elegantYU
  github_repo: myGitment
  client_id: d67d27c34a570a11c1d5
  client_secret: 36122bfcba6b042bd5faae8dacd45de24ed351bb
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_pro

# Disqus
disqus:
  shortname: # your shortname

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 说点什么 # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive: 
  banner_img: https://w.wallhaven.cc/full/43/wallhaven-43qrld.jpg
  banner_img_height: 80  # available: 0 - 100

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  banner_img: https://w.wallhaven.cc/full/nz/wallhaven-nzymgv.jpg
  banner_img_height: 100  # available: 0 - 100
  avatar: https://w.wallhaven.cc/full/d5/wallhaven-d5dpw3.png
  name: 胡不语
  introduce: 要想求仙术，哪能怕吃苦啊
  icons: 
    github: https://github.com/elegantYU
    twitter: https://twitter.com